export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_iNGREDIENT = 'REMOVE_iNGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';